server:
  port: 8000
  servlet:
    context-path: /
spring:
  datasource:
    data-password:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
      #serialization:
      #格式化输出
      #indent_output: true
      #deserialization:
      #允许对象忽略json中不存在的属性
      #fail_on_unknown_properties: false
      #parser:
    #允许出现特殊字符和转义符
    #allow_unquoted_control_chars: true
    #允许出现单引号
    #allow_single_quotes: true
    #设置空如何序列化
    #defaultPropertyInclusion: NON_EMPTY

  #配置 Jpa
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        session_factory:
          statement_inspector: com.ratel.modules.SqlStatementInspector
#          interceptor: com.ratel.framework.domain.interceptor.HibernateInterceptor

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

mybatis:
  # 重要配置
  type-aliases-package: com.ratel.modules.*.mapper
  mapper-locations: classpath*:com.ratel.modules.**.mapper/*.xml


ratel:
  framework:
    security: true
    permission: false

    userId: 222222
    username: admin
    deptId: dddd
    deptName: dddd
    roles: jddd,dddd,dddd

  task:
    pool:
      # 核心线程池大小
      core-pool-size: 10
      # 最大线程数
      max-pool-size: 30
      # 活跃时间
      keep-alive-seconds: 60
      # 队列容量
      queue-capacity: 50

  #邮箱验证码有效时间/分钟
  code:
    expiration: 5

  #登录图形验证码有效时间/分钟
  loginCode:
    enableWeb: false
    enableMobile: false
    expiration: 2

  #缓存设置
  ehcache:
    configFile: ehcache/ehcache-local.xml
    defaultCacheName: sysCache
  #  ehcache:
  #    configFile: cache/ehcache-rmi.xml

  #密码加密传输，前端公钥加密，后端私钥解密
  rsa:
    private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

